# HiHi I'm Kuihao
# This is a workflow to help you define actions which you want to deploy the pages on main branch
# And the code below is edited from https://reurl.cc/Go9k6x

# The name of your workflow
name: deploy gh-pages

# To automatically trigger a workflow, 
# use `on` to define which events can cause the workflow to run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Define a single job below:
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and deploy gh-pages
    
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    #runs-on: ubuntu-latest

    # ???
    #env:
    #  MY_SECRET   : ${{secrets.commit_secret}}
    #  USER_NAME   : githubaction
    #  USER_EMAIL  : githubaction@fake.com
    #  PUBLISH_DIR : ./dist
    
    # ??? global variables?
    strategy:
      matrix:
        node-version: [10.x]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    # `Steps` can do three types of behaviors:
    # * `run` commands (CLI commands in OS)
    # * `uses` actions (offer by Github workflow or contributors)
    # * `with` to setting extensive variables (? not very sure...)
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # to check details: https://github.com/actions/checkout
      
      # Install node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js npm (Node Package Manager) dependencies 
        run: npm install

      - name: npm init
        run: npm init -y

      - name: Run build task
        run: npm run build --if-present
      
      #- name: Creates a build directory with a production build of your app.
      #  run: npm run build
      #  env:
      #    CI: false

      #- name: npm run build
      #  run: |
      #    npm run gulp m
      #    npm run build
      
      # use actions-gh-pages to deploy dist to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github will auto-generate a token for this job and use it 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      #- name: Commit files
      #  run: |
      #    cd $PUBLISH_DIR
      #    git init
      #    git config --local user.name $USER_NAME
      #    git config --local user.email $USER_EMAIL
      #    git status
      #    git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
      #    git checkout -b gh-pages
      #    git add --all
      #    git commit -m "deploy to Github pages"
      #    git push origin gh-pages -f
      #    echo 😎 deploy gh-pages complete.